/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardPaymentDialog: typeof import('./components/CardPaymentDialog.vue')['default']
    CartCard: typeof import('./components/CartCard.vue')['default']
    DeliveryAddressDialog: typeof import('./components/DeliveryAddressDialog.vue')['default']
    GreenImagePanelLayout: typeof import('./components/GreenImagePanelLayout.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ModalPageShell: typeof import('./components/ModalPageShell.vue')['default']
    PaymentDialog: typeof import('./components/PaymentDialog.vue')['default']
    ProductCardDialog: typeof import('./components/ProductCardDialog.vue')['default']
    ProductGrid: typeof import('./components/ProductGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopLayout: typeof import('./components/ShopLayout.vue')['default']
    ThankYouDialog: typeof import('./components/ThankYouDialog.vue')['default']
  }
}
