/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AboutPage': RouteRecordInfo<'/AboutPage', '/AboutPage', Record<never, never>, Record<never, never>>,
    '/AdminLogin': RouteRecordInfo<'/AdminLogin', '/AdminLogin', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/FruitPage': RouteRecordInfo<'/FruitPage', '/FruitPage', Record<never, never>, Record<never, never>>,
    '/HomePage': RouteRecordInfo<'/HomePage', '/HomePage', Record<never, never>, Record<never, never>>,
    '/MadeProductPage': RouteRecordInfo<'/MadeProductPage', '/MadeProductPage', Record<never, never>, Record<never, never>>,
    '/RegisterPAge': RouteRecordInfo<'/RegisterPAge', '/RegisterPAge', Record<never, never>, Record<never, never>>,
    '/ShopPage': RouteRecordInfo<'/ShopPage', '/ShopPage', Record<never, never>, Record<never, never>>,
    '/VegetablePage': RouteRecordInfo<'/VegetablePage', '/VegetablePage', Record<never, never>, Record<never, never>>,
    '/WelcomePage': RouteRecordInfo<'/WelcomePage', '/WelcomePage', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/AboutPage.vue': {
      routes: '/AboutPage'
      views: never
    }
    'src/pages/AdminLogin.vue': {
      routes: '/AdminLogin'
      views: never
    }
    'src/pages/Dashboard.vue': {
      routes: '/Dashboard'
      views: never
    }
    'src/pages/FruitPage.vue': {
      routes: '/FruitPage'
      views: never
    }
    'src/pages/HomePage.vue': {
      routes: '/HomePage'
      views: never
    }
    'src/pages/MadeProductPage.vue': {
      routes: '/MadeProductPage'
      views: never
    }
    'src/pages/RegisterPAge.vue': {
      routes: '/RegisterPAge'
      views: never
    }
    'src/pages/ShopPage.vue': {
      routes: '/ShopPage'
      views: never
    }
    'src/pages/VegetablePage.vue': {
      routes: '/VegetablePage'
      views: never
    }
    'src/pages/WelcomePage.vue': {
      routes: '/WelcomePage'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
